### PR TITLE
chore: Add some Python caches to `.gitignore`

### PR DESCRIPTION
**Pull request by StevenMaude**

### CODE REVIEW

**Comment by madwort** [comment]
do we have a template gitignore anywhere that should be updated? and/or other repos that could use this addition?

**Comment by StevenMaude** [comment]
> do we have a template gitignore anywhere that should be updated? and/or other repos that could use this addition?

This is a good question, and I had a similar thought of how we keep these in sync. I'm not sure if there's a nice, clean way except syncing by hand.

It's this template originally: https://github.com/opensafely-core/repo-template

I can put a PR in there too.

**Comment by madwort** [comment]
Cool, a PR in the template repo sounds good enough for me 👍

**Comment by StevenMaude** [comment]
Actually, this isn't necessary as both caches should actually end up with a `.gitignore` as @ghickman pointed out in Slack.

Copy-paste of my response there:

> 1. The `.mypy_cache` directory I had for `databuilder` didn't have a `.gitignore`. I deleted the directory and re-ran `mypy`, then it appeared. It might have been because I never actually ran `mypy` to completion locally, and just exited early. Not sure.
> 2. Given 1, I just added `.pytest_cache` reflexively after looking at GitHub's Python `.gitignore`, but you're correct in that `.pytest_cache` creates a `.gitignore` too.

**Pull request closed without merging**
